In [5]:
import numpy as np
import pyproj

In [14]:
mid_point = [1.3662438032069444, 103.83320768517596]
num_points = 2
bearing = 0
bearings = np.arange(0, 360, 360/num_points)

geodesic = pyproj.Geod(ellps='WGS84')

grid_points = [mid_point]

longs, lats, fwd_az = geodesic.fwd(lons=[mid_point[1]]*num_points, lats=[mid_point[0]]*num_points, az=bearings, dist=[5*1000]*num_points)

longs.append(mid_point[1])
lats.append(mid_point[0])
grid_points = np.vstack((lats,longs)).transpose()


grid_points

 

array([[  1.41146201, 103.83320769],
       [  1.32102558, 103.83320769],
       [  1.3662438 , 103.83320769]])

In [16]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
result = np.tile(array1, (len(array2), 1))
result

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [17]:
for i in range(len(array2)):
   result[i::len(array2)] = array2[i]
result

array([[5, 6],
       [7, 8],
       [5, 6],
       [7, 8]])

In [4]:
a = np.array([[1, 2], [3, 4]])

# Repeat each row twice
result = np.repeat(a, 2, axis=0)

print(result)

[[1 2]
 [1 2]
 [3 4]
 [3 4]]


In [83]:
locations = [
    {'coor': [1,2], 'freq': 1, 'travel_type': 1},
    {'coor': [3,4], 'freq': 2, 'travel_type': 2}
]


travel_location = np.array([[x['coor'][0], x['coor'][1]] for x in locations])
travel_frequency = np.array([[x['freq']]for x in locations])
travel_type = np.array([[x['travel_type'] ]for x in locations])

search_locations = np.array([
    [1,2],
    [3,4]
])

num_search_location = len(search_locations)
num_locations = len(locations)


In [84]:
travel_type

array([[1],
       [2]])

In [85]:
travel_location = np.tile(travel_location, (num_search_location,1))
travel_frequency = np.tile(travel_frequency, (num_search_location,1))
travel_type = np.tile(travel_type, (num_search_location,1))

expand_search_array = np.repeat(search_locations, num_locations, axis=0)

In [86]:
travel_location

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [87]:
travel_type

array([[1],
       [2],
       [1],
       [2]])

In [88]:
expand_search_array

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [115]:
travel_time = np.array([[1],[1],[1],[1]])

costs = np.exp(travel_time)*travel_frequency
costs

array([[2.71828183],
       [5.43656366],
       [2.71828183],
       [5.43656366]])

In [116]:
expand_search_array

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [126]:
cost_vectors = np.array([[1,2],[3,4],[5,6],[7,8]])

In [130]:

result = np.array([np.sum(cost_vectors[np.all(expand_search_array==val, axis=1)],axis=0) for val in search_locations])
result


array([[ 4,  6],
       [12, 14]])

In [122]:
for val in search_locations:
    print(np.all(expand_search_array==val, axis=1))

[ True  True False False]
[False False  True  True]


In [91]:
search_locations

array([[1, 2],
       [3, 4]])

In [95]:
search_locations[:,1]

array([2, 4])

In [96]:
geodesic = pyproj.Geod(ellps='WGS84')
fwd_azimuth,back_azimuth,distance = geodesic.inv(
    lats1=expand_search_array[:,0], 
    lons1=expand_search_array[:,1], 
    lats2=travel_location[:,0], 
    lons2=travel_location[:,1]
)

In [98]:
fwd_azimuth.reshape(4,1)

array([[ 180.        ],
       [  45.14416881],
       [-134.78601439],
       [ 180.        ]])

In [105]:
unqiue = np.unique(expand_search_array, axis=0)

array([[1, 2],
       [3, 4]])

In [106]:
expand_search_array

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [109]:
[[expand_search_array == val] for val in search_locations]

[[array([[ True,  True],
         [ True,  True],
         [False, False],
         [False, False]])],
 [array([[False, False],
         [False, False],
         [ True,  True],
         [ True,  True]])]]

In [140]:
a = np.array([[1,2],[-3,4]])

# Calculate the bearing for each element in the array
bearings = np.degrees(np.arctan2(a[:,0], a[:,1])).reshape(-1,1)+90

print(bearings)

[[116.56505118]
 [ 53.13010235]]


In [132]:
costs

array([[2.71828183],
       [5.43656366],
       [2.71828183],
       [5.43656366]])

In [133]:
azimuth = np.array([[-1],[-1],[1],[1]])

In [135]:
v_cost_vectors =  costs * -1*azimuth
h_cost_vectors = costs * azimuth
cost_vectors = np.hstack([v_cost_vectors, h_cost_vectors])
cost_vectors

array([[ 2.71828183, -2.71828183],
       [ 5.43656366, -5.43656366],
       [-2.71828183,  2.71828183],
       [-5.43656366,  5.43656366]])

In [141]:
geodesic.fwd(lats=1.36141933468784, lons=103.83210157865061, az=-90, dist=5*1000)

(103.78717321670398, 1.3614189134670607, 89.99893254652814)

In [142]:
from onemap_client import OneMapClient

from dotenv import load_dotenv
load_dotenv()

email = os.environ['ONE_MAP_API_EMAIL']
password = os.environ['ONE_MAP_API_PASSWORD']

Client = OneMapClient(email, password)
token = Client.get_token(email, password)
print(token)

ModuleNotFoundError: No module named 'onemap_client'

In [144]:
resultant_cost_vectors = np.array([[-1.19523865,0.66428467]])

In [145]:
np.degrees(np.arctan2(resultant_cost_vectors[:,0], resultant_cost_vectors[:,1])).reshape(-1,1)+90

array([[29.06424436]])

In [151]:
np.degrees(np.arctan2(resultant_cost_vectors[:,0], resultant_cost_vectors[:,1])).reshape(-1,1)+90

array([[-60.93575564]])

In [160]:
v = -1.19523865
h = -0.66428467

In [161]:
np.degrees(np.arctan2(h, v))

-150.93575564031786

In [162]:
import folium

In [202]:
coors =  [[1.3193790935628127, 103.82903068459888], [1.356772075222052, 103.79696381492978], [1.3577535204191273, 103.8689502597439], [1.3585991366700532, 103.82418638183557], [1.3978697200051884, 103.82475361410458], [1.327586913808211, 103.82525781941514], [1.356088080540262, 103.80592373172115], [1.3590184107441585, 103.86005292254282], [1.3607951911598795, 103.81546966369723], [1.3940769179579147, 103.81659624290974], [1.3332066585391096, 103.81821771090041], [1.3552965488240303, 103.8148749000832], [1.3603196561478315, 103.85116075784266], [1.3629866158545918, 103.80675178747822], [1.3866605022617986, 103.8217384793293], [1.3385783484574036, 103.81098895418192], [1.3585678272897057, 103.80649769643551], [1.3615289376958002, 103.84225578159628], [1.3651581015632206, 103.79802897927871], [1.3843686983916998, 103.81304603572472], [1.3458650335840432, 103.80566686604716], [1.3626205126416155, 103.83333580164654], [1.3672856792096468, 103.78929548800059], [1.3825272587474529, 103.80424852719037], [1.3524265119206746, 103.79948308747836], [1.3636914793516919, 103.82441335187363], [1.3655897082659072, 103.79812175960559], [1.3811527070080543, 103.79536717608906], [1.3521432440109575, 103.80846431723309], [1.364879173235534, 103.81550549547346], [1.3676320717777737, 103.7893682064449], [1.3662387384020143, 103.80662192740253], [1.3658959731067113, 103.7981867737696], [1.3678777718587944, 103.78941948688252], [1.3678310150991506, 103.79777660516429], [1.3694599110490622, 103.78893786206866], [1.3661132349693432, 103.79823248095015]]

m = folium.Map(
    location=(1.3674754117016408, 103.81093951150724), 
    zoom_start=11,
    min_zoom=11
)

for i, coor in enumerate(coors):
    m.add_child(
        folium.Marker(
            location = coor,
            tooltip=i
        )
    )
m

In [192]:
import numpy as np

a = np.array([[-1],[-1],[-1],[-1]])
b = np.array([[0],[1],[2],[3]])

# Create a boolean mask where True corresponds to elements in 'a' that are not -1
mask = a != [-1]

mask = np.all(mask, axis=1)
# Use the mask to index into 'b'
result = b[mask]

print(result)

[]


In [193]:
mask

array([False, False, False, False])

In [194]:
np.any(mask)

False

In [177]:
np.unique(expand_search_array, axis=0)

array([[1, 2],
       [3, 4]])

In [198]:
cost_vectors = np.array([[ 28.86319184, -17.96608517],
 [-1.00790728,11.89721101],
 [3.90371043,-26.26883033],
 [ -0.42292976,  -1.62547499]])



In [200]:
np.degrees(np.arctan2(cost_vectors[:,1], cost_vectors[:,0])).reshape(-1,1)

array([[ -31.90047291],
       [  94.84241796],
       [ -81.54735322],
       [-104.58432752]])